version: '3'
services: 
  #Ubuntu
  os:
    build:
        context: .
        dockerfile: Dockerfile
    image: lod2007/pyspark
    container_name: pyspark
    restart: unless-stopped
    tty: true
    # environment:
    #   SERVICE_NAME: app
    #   SERVICE_TAGS: dev
    working_dir: /home
    volumes:
        - ./work:/home
    networks:
      - app-network

#Docker Networks
networks:
    app-network:
      driver: bridge