version: '3'
services: 
  #Ubuntu
  os:
    build:
        context: .
        dockerfile: Dockerfile
    image: lod2007/pyspark
    container_name: pyspark
    restart: unless-stopped
    tty: true
    working_dir: /db_home
    volumes:
        - ./work:/work
        - ./db_home:/db_home
    networks:
      - app-network

#Docker Networks
networks:
    app-network:
      driver: bridge